spring:
  datasource:
    # URL подключения к базе данных PostgreSQL
    url: jdbc:postgresql://localhost:5432/CosmicIntrigueTest
    # Имя пользователя базы данных PostgreSQL
    username: ci_test
    # Пароль пользователя базы данных PostgreSQL
    password: ci_testSQLPopov
    # Драйвер для подключения к PostgreSQL
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Автогенерация схемы Hibernate
    generate-ddl: true

    hibernate:
      # Опция управления схемой базы данных
      ddl-auto: create-drop
    # Показываем запросы SQL
    show-sql: true
