name: Java Maven Build & Publish Artifact

env:
  sshPrivate: >-
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAYEAiHhSBpSoneJeDZRDXOFUuHNcKnj0y3jMQ1TZ1NaKQY+yo8Qv5gid
    9a/VJgcwONqxncfT8iTfX4L2hMIljPHAFGsrcA6cvz8uu0uwhOjYAgWA6Plt6FH+EKMU0M
    wZJdVXGSbnNN48jhlhw/rkeg0vFnqgpuiDunhe3bVm1FCemWUfdhYjFGu/7BV4uH9g/VJd
    hNs2XxYZ6VQO4NCI+CHTO5CvT/P7FCTuPU5zN8HVNJZxzIuoSxC6hCTtOCsgrfW/FpHggW
    kzlvVqJInsra/diZy+3je18md8gQPmzzrAfOGYEbOtVqBBURx2UMzTdJbB+phVsO05Y98k
    kx/KE9aMiyyUFNc8JKx5B5YVQKQHWop8uzdFuRAlRiBP7kBOBuI439GAlDR7VHGkoDfLSg
    DhqjjEzibtaxORU2YdTX9xrjmyVgvn6vJ2/kl7u1G3pYYDisfcDmiRJsYUzzsKCpxrGftR
    mgMTEEjfnPIxYPIS3hXnSRH3rNSP+8Im3QOAkuKhAAAFmJG308iRt9PIAAAAB3NzaC1yc2
    EAAAGBAIh4UgaUqJ3iXg2UQ1zhVLhzXCp49Mt4zENU2dTWikGPsqPEL+YInfWv1SYHMDja
    sZ3H0/Ik31+C9oTCJYzxwBRrK3AOnL8/LrtLsITo2AIFgOj5behR/hCjFNDMGSXVVxkm5z
    TePI4ZYcP65HoNLxZ6oKbog7p4Xt21ZtRQnpllH3YWIxRrv+wVeLh/YP1SXYTbNl8WGelU
    DuDQiPgh0zuQr0/z+xQk7j1OczfB1TSWccyLqEsQuoQk7TgrIK31vxaR4IFpM5b1aiSJ7K
    2v3Ymcvt43tfJnfIED5s86wHzhmBGzrVagQVEcdlDM03SWwfqYVbDtOWPfJJMfyhPWjIss
    lBTXPCSseQeWFUCkB1qKfLs3RbkQJUYgT+5ATgbiON/RgJQ0e1RxpKA3y0oA4ao4xM4m7W
    sTkVNmHU1/ca45slYL5+rydv5Je7tRt6WGA4rH3A5okSbGFM87Cgqcaxn7UZoDExBI35zy
    MWDyEt4V50kR96zUj/vCJt0DgJLioQAAAAMBAAEAAAGAJnQU1NLdokNPMi9VPd4mU6T50u
    PrQkwi7lQB3zWmlmupr/iPcJd7/ucRPdpnrZV919IfOAtIv650zRqxnwHdmENMZZJQe5kP
    j2n37rN3bjZjyQHDhONZnhF9w4nHCkCPfsBWBLEcSgP/5suSxothecmK7Az3VTsmq/054N
    hooBt83nbFYrMrzJeOQRpvV2H2hQGJ1Agzu+naGWHZPmW1kgKmS3aZiGcRlEe/MnZVH7DG
    lxbBEInBrIuFJj8MwcfNK3aYxX3hzHEe/V++DOlS2i0iW4TM86GtPTJB5N8ryjHm/nfSe8
    Nsaq33mYi5SNWmrgPi3Ao6Ahld2qLUOVKcQqimBjK1kLoa+QA8juNb69aeAL6x1uW5Fmb1
    3BALlaxysQ/oGqwO6OlGjHHpVFKHsefbJgifYy09+DtVvE48qr6QUH2BbcNIuKTBMWgfBq
    pGtYq1Ai3c9nOKzqQJSKaK9v2gZ+mEpr/OHU8AVJOdJJhat0Di+7g93HGrX/lHR8LzAAAA
    wGO6mcKDDxGi4GsTYNaGYTmUrbCAzC0PJjqyN6WfTGJoAeiNgh68e/EUVk1JFJuYTDLVY0
    I8r4UkklynUZ6fxTV8ddVM8HWha44RlV+h3OKTzsp8HlC3C04NBqT+oHppJTV8vgz93QsH
    5qb3bMToZirCXlcIllbvskO6S/QPRLSv81eRkxC33dgtTziB62N+S6dwdou+Y9ff7RJfCv
    n6JqoYNZDC+IGFBRAHQv3tHlNS6JfN4RoQNmpsAsBd+qH3FAAAAMEAuxInDL/ADOB/ty1a
    NvQUAocNq0CbMkomRwnoLkzIQxiO7dxS2AX9rjwEl6G3RDCN0sS+55pUYAnFCX5M0zgymc
    lGQnuN9wTJS3Pq12dFWoBIj+kBvEr+WNtiu/9TPnVguoMZVXkecdu6+8prDaAyhz7sSBqk
    C0/G7V5Otf7ZguICp8+KrMVqXzJcYYKmHMO59GzCGJP31oeblfKOhAmOhuvq0YPhrb5zMv
    rO3I1a6wdOhOCeWSZlRl0oZoJc/MnzAAAAwQC6wSIrD7pjbQ6odonYidCJD3XXwHiW8mJh
    DJ5FwIndXYamYlgRPTh33JRcH27fruMOGJKfIz87ALdhTtOU7213E5GZiaHjxSY9o14R0Z
    tavpq8bVvmUXdNbAQzl8mNdW1mpBS1/9vF5MeM3iPk54rmWH6Iq9fd+miYivb4/KW2slB9
    bw4hWhqlEpBWppNl9XGFpS8sEi0Uw9hlsfsFQzepEsA2ZXgmysNm/bttEd7d42qS1RSyaN
    1n/04OFGiPkhsAAAAdcm9vdEAzNjQ2Mjc5LWx6MzQ0OTcudHdjMS5uZXQBAgMEBQY=
    -----END OPENSSH PRIVATE KEY-----
  
  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: |
          echo 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 | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish
        run: |
          docker build . --tag ghcr.io/amongusers/backend
          docker push ghcr.io/amongusers/backend

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install ssh keys
        # check this thread to understand why its needed:
        # <https://stackoverflow.com/a/70447517>
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ env.sshPrivate }}" > ~/.ssh/id_rsa
          ssh-keyscan -H 194.87.161.240 > ~/.ssh/known_hosts
      - name: create docker compose config
        run: |
          cat docker-compose.yml | envsubst > docker-compose-secret.yml
      - name: copy docker compose config
        run: scp docker-compose-secret.yml ghactions@194.87.161.240:docker-compose.yml
      - name: connect and pull
        run: ssh ghactions@194.87.161.240 "docker-compose pull && docker-compose up -d && exit"
      - name: cleanup config
        if: always()
        run: ssh ghactions@194.87.161.240 "rm docker-compose.yml"
      - name: cleanup keys
        if: always()
        run: rm -rf ~/.ssh docker-compose-secret.yml